import { currentLang } from "./languages";
export const isoCountries = {
  pl: {
    AF: "Afganistan",
    AX: "Wyspy Alandzkie",
    AL: "Albania",
    DZ: "Algieria",
    AS: "Samoa Amerykańskie",
    AD: "Andora",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarktyda",
    AG: "Antigua i Barbuda",
    AR: "Argentyna",
    AM: "Armenia",
    AW: "Aruba",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbejdżan",
    BS: "Bahamy",
    BH: "Bahrajn",
    BD: "Bangladesz",
    BB: "Barbados",
    BY: "Białoruś",
    BE: "Belgia",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermudy",
    BT: "Bhutan",
    BO: "Boliwia",
    BA: "Bośnia i Hercegowina",
    BW: "Botswana",
    BV: "Wyspa Bouvet",
    BR: "Brazylia",
    IO: "Brytyjskie Terytorium Oceanu Indyjskiego",
    BN: "Brunei Darussalam",
    BG: "Bułgaria",
    BF: "Burkina Faso",
    BI: "Burundi",
    KH: "Kambodża",
    CM: "Kamerun",
    CA: "Kanada",
    CV: "Republika Zielonego Przylądka",
    KY: "Kajmany",
    CF: "Republika Środkowoafrykańska",
    TD: "Czad",
    CL: "Chile",
    CN: "Chiny",
    CX: "Wyspa Bożego Narodzenia",
    CC: "Wyspy Kokosowe (Keelinga)",
    CO: "Kolumbia",
    KM: "Komory",
    CG: "Kongo",
    CD: "Kongo, Republika Demokratyczna",
    CK: "Wyspy Cooka",
    CR: "Kostaryka",
    CI: "Wybrzeże Kości Słoniowej",
    HR: "Chorwacja",
    CU: "Kuba",
    CY: "Cypr",
    CZ: "Republika Czeska",
    DK: "Dania",
    DJ: "Dżibuti",
    DM: "Dominika",
    DO: "Republika Dominikańska",
    WE: "Ekwador",
    EG: "Egipt",
    SV: "El Salvador",
    GQ: "Gwinea Równikowa",
    ER: "Erytrea",
    EE: "Estonia",
    ET: "Etiopia",
    FK: "Falklandy (Malwiny)",
    FO: "Wyspy Owcze",
    FJ: "Fidżi",
    FI: "Finlandia",
    FR: "Francja",
    GF: "Gujana Francuska",
    PF: "Polinezja Francuska",
    TF: "Francuskie Terytoria Południowe",
    GA: "Gabon",
    GM: "Gambia",
    GE: "Georgia",
    DE: "Niemcy",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Grecja",
    GL: "Grenlandia",
    GD: "Grenada",
    GP: "Gwadelupa",
    GU: "Guam",
    GT: "Gwatemala",
    GG: "Guernsey",
    GN: "Gwinea",
    GW: "Gwinea Bissau",
    GY: "Gujana",
    HT: "Haiti",
    HM: "Heard Island & Mcdonald Islands",
    VA: "Stolica Apostolska (Państwo Watykańskie)",
    HN: "Honduras",
    HK: "Hongkong",
    HU: "Węgry",
    IS: "Islandia",
    IN: "Indie",
    ID: "Indonezja",
    IR: "Iran, Islamska Republika",
    IQ: "Irak",
    IE: "Irlandia",
    IM: "Wyspa Man",
    IL: "Izrael",
    IT: "Włochy",
    JM: "Jamajka",
    JP: "Japonia",
    JE: "Jersey",
    JO: "Jordan",
    KZ: "Kazachstan",
    KE: "Kenia",
    KI: "Kiribati",
    KR: "Korea",
    KW: "Kuwejt",
    KG: "Kirgistan",
    LA: "Laotańska Republika Ludowo-Demokratyczna",
    LV: "Łotwa",
    LB: "Liban",
    LS: "Lesotho",
    LR: "Liberia",
    LY: "Libijska Arabska Dżamahirija",
    LI: "Liechtenstein",
    LT: "Litwa",
    LU: "Luksemburg",
    MO: "Makao",
    MK: "Macedonia",
    MG: "Madagaskar",
    MW: "Malawi",
    MY: "Malezja",
    MV: "Malediwy",
    ML: "Mali",
    MT: "Malta",
    MH: "Wyspy Marshalla",
    MQ: "Martynika",
    MR: "Mauretania",
    MU: "Mauritius",
    YT: "Majotta",
    MX: "Meksyk",
    FM: "Mikronezja, Sfederowane Stany",
    MD: "Mołdawia",
    MC: "Monako",
    MN: "Mongolia",
    ME: "Czarnogóra",
    MS: "Montserrat",
    MA: "Maroko",
    MZ: "Mozambik",
    MM: "Myanmar",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NL: "Holandia",
    AN: "Antyle Holenderskie",
    NC: "Nowa Kaledonia",
    NZ: "Nowa Zelandia",
    NI: "Nikaragua",
    NE: "Niger",
    NG: "Nigeria",
    NU: "Niue",
    NF: "Wyspa Norfolk",
    MP: "Mariany Północne",
    NIE: "Norwegia",
    OM: "Oman",
    PK: "Pakistan",
    PW: "Palau",
    PS: "Terytorium Palestyńskie, okupowane",
    PA: "Panama",
    PG: "Papua Nowa Gwinea",
    PY: "Paragwaj",
    PE: "Peru",
    PH: "Filipiny",
    PN: "Pitcairn",
    PL: "Polska",
    PT: "Portugalia",
    PR: "Puerto Rico",
    QA: "Katar",
    RE: "Reunion",
    RO: "Rumunia",
    RU: "Federacja Rosyjska",
    RW: "Rwanda",
    BL: "Saint Barthelemy",
    SH: "Święta Helena",
    KN: "Saint Kitts And Nevis",
    LC: "Saint Lucia",
    MF: "Saint Martin",
    PM: "Saint Pierre And Miquelon",
    VC: "Saint Vincent And Grenadines",
    WS: "Samoa",
    SM: "San Marino",
    ST: "Wyspy Świętego Tomasza i Książęca",
    SA: "Arabia Saudyjska",
    SN: "Senegal",
    RS: "Serbia",
    SC: "Seszele",
    SL: "Sierra Leone",
    SG: "Singapur",
    SK: "Słowacja",
    SI: "Słowenia",
    SB: "Wyspy Salomona",
    SO: "Somalia",
    ZA: "Republika Południowej Afryki",
    GS: "South Georgia And Sandwich Isl.",
    ES: "Hiszpania",
    LK: "Sri Lanka",
    SD: "Sudan",
    SR: "Surinam",
    SJ: "Svalbard And Jan Mayen",
    SZ: "Suazi",
    SE: "Szwecja",
    CH: "Szwajcaria",
    SY: "Syryjska Republika Arabska",
    TW: "Tajwan",
    TJ: "Tadżykistan",
    TZ: "Tanzania",
    TH: "Tajlandia",
    TL: "Timor Wschodni",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trynidad i Tobago",
    TN: "Tunezja",
    TR: "Turcja",
    TM: "Turkmenistan",
    TC: "Wyspy Turks i Caicos",
    TV: "Tuvalu",
    UG: "Uganda",
    UA: "Ukraina",
    AE: "Zjednoczone Emiraty Arabskie",
    GB: "Wielka Brytania",
    USA: "Stany Zjednoczone",
    UM: "Wyspy Dalekie Stanów Zjednoczonych",
    UY: "Urugwaj",
    UZ: "Uzbekistan",
    VU: "Vanuatu",
    VE: "Wenezuela",
    VN: "Wietnam",
    VG: "Wyspy Dziewicze, Brytyjskie",
    VI: "Wyspy Dziewicze Stanów Zjednoczonych",
    WF: "Wallis And Futuna",
    EH: "Sahara Zachodnia",
    YE: "Jemen",
    ZR: "Zair",
    ZM: "Zambia",
    ZW: "Zimbabwe"
  },
  eng: {
    AF: "Afghanistan",
    AX: "Aland Islands",
    AL: "Albania",
    DZ: "Algeria",
    AS: "American Samoa",
    AD: "Andorra",
    AO: "Angola",
    AI: "Anguilla",
    AQ: "Antarctica",
    AG: "Antigua And Barbuda",
    AR: "Argentina",
    AM: "Armenia",
    AW: "Aruba",
    AU: "Australia",
    AT: "Austria",
    AZ: "Azerbaijan",
    BS: "Bahamas",
    BH: "Bahrain",
    BD: "Bangladesh",
    BB: "Barbados",
    BY: "Belarus",
    BE: "Belgium",
    BZ: "Belize",
    BJ: "Benin",
    BM: "Bermuda",
    BT: "Bhutan",
    BO: "Bolivia",
    BA: "Bosnia And Herzegovina",
    BW: "Botswana",
    BV: "Bouvet Island",
    BR: "Brazil",
    IO: "British Indian Ocean Territory",
    BN: "Brunei Darussalam",
    BG: "Bulgaria",
    BF: "Burkina Faso",
    BI: "Burundi",
    KH: "Cambodia",
    CM: "Cameroon",
    CA: "Canada",
    CV: "Cape Verde",
    KY: "Cayman Islands",
    CF: "Central African Republic",
    TD: "Chad",
    CL: "Chile",
    CN: "China",
    CX: "Christmas Island",
    CC: "Cocos (Keeling) Islands",
    CO: "Colombia",
    KM: "Comoros",
    CG: "Congo",
    CD: "Congo, Democratic Republic",
    CK: "Cook Islands",
    CR: "Costa Rica",
    CI: "Cote D'Ivoire",
    HR: "Croatia",
    CU: "Cuba",
    CY: "Cyprus",
    CZ: "Czech Republic",
    DK: "Denmark",
    DJ: "Djibouti",
    DM: "Dominica",
    DO: "Dominican Republic",
    EC: "Ecuador",
    EG: "Egypt",
    SV: "El Salvador",
    GQ: "Equatorial Guinea",
    ER: "Eritrea",
    EE: "Estonia",
    ET: "Ethiopia",
    FK: "Falkland Islands (Malvinas)",
    FO: "Faroe Islands",
    FJ: "Fiji",
    FI: "Finland",
    FR: "France",
    GF: "French Guiana",
    PF: "French Polynesia",
    TF: "French Southern Territories",
    GA: "Gabon",
    GM: "Gambia",
    GE: "Georgia",
    DE: "Germany",
    GH: "Ghana",
    GI: "Gibraltar",
    GR: "Greece",
    GL: "Greenland",
    GD: "Grenada",
    GP: "Guadeloupe",
    GU: "Guam",
    GT: "Guatemala",
    GG: "Guernsey",
    GN: "Guinea",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HT: "Haiti",
    HM: "Heard Island & Mcdonald Islands",
    VA: "Holy See (Vatican City State)",
    HN: "Honduras",
    HK: "Hong Kong",
    HU: "Hungary",
    IS: "Iceland",
    IN: "India",
    ID: "Indonesia",
    IR: "Iran, Islamic Republic Of",
    IQ: "Iraq",
    IE: "Ireland",
    IM: "Isle Of Man",
    IL: "Israel",
    IT: "Italy",
    JM: "Jamaica",
    JP: "Japan",
    JE: "Jersey",
    JO: "Jordan",
    KZ: "Kazakhstan",
    KE: "Kenya",
    KI: "Kiribati",
    KR: "Korea",
    KW: "Kuwait",
    KG: "Kyrgyzstan",
    LA: "Lao People's Democratic Republic",
    LV: "Latvia",
    LB: "Lebanon",
    LS: "Lesotho",
    LR: "Liberia",
    LY: "Libyan Arab Jamahiriya",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MO: "Macao",
    MK: "Macedonia",
    MG: "Madagascar",
    MW: "Malawi",
    MY: "Malaysia",
    MV: "Maldives",
    ML: "Mali",
    MT: "Malta",
    MH: "Marshall Islands",
    MQ: "Martinique",
    MR: "Mauritania",
    MU: "Mauritius",
    YT: "Mayotte",
    MX: "Mexico",
    FM: "Micronesia, Federated States Of",
    MD: "Moldova",
    MC: "Monaco",
    MN: "Mongolia",
    ME: "Montenegro",
    MS: "Montserrat",
    MA: "Morocco",
    MZ: "Mozambique",
    MM: "Myanmar",
    NA: "Namibia",
    NR: "Nauru",
    NP: "Nepal",
    NL: "Netherlands",
    AN: "Netherlands Antilles",
    NC: "New Caledonia",
    NZ: "New Zealand",
    NI: "Nicaragua",
    NE: "Niger",
    NG: "Nigeria",
    NU: "Niue",
    NF: "Norfolk Island",
    MP: "Northern Mariana Islands",
    NO: "Norway",
    OM: "Oman",
    PK: "Pakistan",
    PW: "Palau",
    PS: "Palestinian Territory, Occupied",
    PA: "Panama",
    PG: "Papua New Guinea",
    PY: "Paraguay",
    PE: "Peru",
    PH: "Philippines",
    PN: "Pitcairn",
    PL: "Poland",
    PT: "Portugal",
    PR: "Puerto Rico",
    QA: "Qatar",
    RE: "Reunion",
    RO: "Romania",
    RU: "Russian Federation",
    RW: "Rwanda",
    BL: "Saint Barthelemy",
    SH: "Saint Helena",
    KN: "Saint Kitts And Nevis",
    LC: "Saint Lucia",
    MF: "Saint Martin",
    PM: "Saint Pierre And Miquelon",
    VC: "Saint Vincent And Grenadines",
    WS: "Samoa",
    SM: "San Marino",
    ST: "Sao Tome And Principe",
    SA: "Saudi Arabia",
    SN: "Senegal",
    RS: "Serbia",
    SC: "Seychelles",
    SL: "Sierra Leone",
    SG: "Singapore",
    SK: "Slovakia",
    SI: "Slovenia",
    SB: "Solomon Islands",
    SO: "Somalia",
    ZA: "South Africa",
    GS: "South Georgia And Sandwich Isl.",
    ES: "Spain",
    LK: "Sri Lanka",
    SD: "Sudan",
    SR: "Suriname",
    SJ: "Svalbard And Jan Mayen",
    SZ: "Swaziland",
    SE: "Sweden",
    CH: "Switzerland",
    SY: "Syrian Arab Republic",
    TW: "Taiwan",
    TJ: "Tajikistan",
    TZ: "Tanzania",
    TH: "Thailand",
    TL: "Timor-Leste",
    TG: "Togo",
    TK: "Tokelau",
    TO: "Tonga",
    TT: "Trinidad And Tobago",
    TN: "Tunisia",
    TR: "Turkey",
    TM: "Turkmenistan",
    TC: "Turks And Caicos Islands",
    TV: "Tuvalu",
    UG: "Uganda",
    UA: "Ukraine",
    AE: "United Arab Emirates",
    GB: "United Kingdom",
    US: "United States",
    UM: "United States Outlying Islands",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VU: "Vanuatu",
    VE: "Venezuela",
    VN: "Viet Nam",
    VG: "Virgin Islands, British",
    VI: "Virgin Islands, U.S.",
    WF: "Wallis And Futuna",
    EH: "Western Sahara",
    YE: "Yemen",
    ZR: "Zaire",
    ZM: "Zambia",
    ZW: "Zimbabwe"
  }
};

export const getCountryName = countryCode => {
  if (isoCountries[currentLang()].hasOwnProperty(countryCode)) {
    return isoCountries[currentLang()][countryCode];
  } else {
    return countryCode;
  }
};

export const getEnglishCountryName = countryCode => {
  if (isoCountries["eng"].hasOwnProperty(countryCode)) {
    return isoCountries["eng"][countryCode];
  } else {
    return countryCode;
  }
};